export const KENYA_COUNTIES = [
  "mombasa",
  "kwale",
  "kilifi",
  "tana river",
  "lamu",
  "taita/taveta",
  "garissa",
  "wajir",
  "mandera",
  "marsabit",
  "isiolo",
  "meru",
  "tharaka-nithi",
  "embu",
  "kitui",
  "machakos",
  "makueni",
  "nyandarua",
  "nyeri",
  "kirinyaga",
  "murang'a",
  "kiambu",
  "turkana",
  "west pokot",
  "samburu",
  "trans nzoia",
  "uasin gishu",
  "elgeyo-marakwet",
  "nandi",
  "baringo",
  "laikipia",
  "nakuru",
  "narok",
  "kajiado",
  "kericho",
  "bomet",
  "kakamega",
  "vihiga",
  "bungoma",
  "busia",
  "siaya",
  "kisumu",
  "homa bay",
  "migori",
  "kisii",
  "nyamira",
  "nairobi",
] as const;

export const PARK_TYPES = [
  "national park",
  "national reserve",
  "forest reserve",
  "community park",
  "private park",
] as const;

export const SOCIAL_PLATFORMS = [
  "facebook",
  "twitter",
  "instagram",
  "linkedin",
  "youtube",
  "tiktok",
  "website",
];

export const CURRENCIES = ["kes", "usd"] as const;
