export const events = [
  {
    name: "name",
    location: "nairobi",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "hiking",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
  {
    name: "name",
    location: "mombasa",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "football",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
  {
    name: "name",
    location: "nairobi",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "running",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
  {
    name: "name",
    location: "mombasa",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "athletics",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
  {
    name: "name",
    location: "nairobi",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "hiking",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
  {
    name: "name",
    location: "mombasa",
    images: ["/dev-data/football.jpg"],
    description: "this is the description of the event",
    type: "running",
    date: "1st December 2024",
    time: "11am -4pm",
    public: "no",
    slots: 20,
  },
];
